# Generated by Django 4.2.7 on 2023-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='No desc', max_length=50)),
                ('author', models.CharField(blank=True, default='No desc', max_length=50)),
                ('year_created', models.IntegerField()),
            ],
        ),
    ]
